execute pathogen#infect()
syntax on
filetype plugin indent on
Helptags

syntax on
set number
let mapleader = ","

set shiftwidth=4
set shiftround
set showmatch
set smartcase
set smarttab
set incsearch
set hlsearch

au GUIEnter * simalt ~x

:set guioptions-=m "remove menu bar
:set guioptions-=T "remove toolbar
:set guioptions-=r "remove right-hand scroll bar
:set guioptions-=L "remove left-hand scroll bar

:set guifont=Monospace\ 10

"NERD TREE CONFIG
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
map <C-n> :NERDTreeToggle<CR>
let g:NERDTreeWinPos = "right"

"GUI only colour scheme
if has('gui_running')
	set background=dark
	colorscheme solarized
endif

"Window navigation shortcuts

noremap <C-Down> <C-W>J
noremap <C-Left> <C-W>H
noremap <C-Up> <C-W>K
noremap <C-Right> <C-W>L

noremap <C-J> <C-W>j
noremap <C-H> <C-W>h
noremap <C-K> <C-W>k
noremap <C-L> <C-W>l


"Workaround for SQL Omni completion messing with my Ctrl-C escape map
let g:ftplugin_sql_omni_key = '<C-X>'

"Auto reload vimrc on save
augroup reload_vimrc " {
	autocmd!
	autocmd BufWritePost $MYVIMRC source $MYVIMRC
augroup END " }

"Backspace config
set backspace=indent,eol,start
:imap <C-BS> <C-W>

"Wrapping options for markdown
augroup markdownWrapping
	autocmd FileType mkd setlocal tw=80
	autocmd FileType mkd setlocal formatoptions+=t
augroup END

let g:vim_markdown_folding_disabled=1

"Shortcut for make command
nnoremap <leader>m :make<ENTER>
" Shortcut to toggle search highlight
nnoremap <F12> :noh<CR>

" Shortcut to rapidly toggle `set list`
nmap <leader>l :set list!<CR>
" Use the same symbols as TextMate for tabstops and EOLs
set listchars=tab:?\ ,eol:¬

" CDC = Change to Directory of Current file
command! CDC cd %:p:h

"Latex options
let g:tex_flavor = "latex"
autocmd FileType tex setlocal tw=80
autocmd FileType tex setlocal formatoptions+=t

"Rainbow parentheses always on
au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces

"Python options
let g:pymode_folding = 0
let g:pymode_lint_ignore = "E501"
let g:pymode_rope_complete_on_dot = 0
